version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
      nodejs: 20
    commands:
      - npm install -g aws-cdk
      - pip install -r infra/requirements.txt
  build:
    commands:
      - cd infra
      - cdk deploy UserServiceBasicInfraStack --require-approval never --outputs-file outputs.json

artifacts:
  files:
    - 'infra/outputs.json'